### ISSUE TITLE
UnboundLocalError: local variable 'search_engine' referenced before assignment`

### ISSUE THREAD

**Issue by kevincw01** [Ayyodeji/Langchain-LLM-PDF-QA#1]
after install and configuration of openai org and secret key id, I load any pdf and get the following error.  I do have billing setup in openai and about $10 of credit.  On the web app I see the error: List Index Out Of Range.  This is an exception caught after trying 'search_engine = await cl.make_async(create_search_engine)(file=file)'

Console Log:
`2024-07-19 03:17:01 - 2 changes detected
2024-07-19 03:18:09 - Anonymized telemetry enabled. See https://docs.trychroma.com/telemetry for more information.
2024-07-19 03:18:09 - No existing DB found in .chromadb, skipping load
2024-07-19 03:18:09 - No existing DB found in .chromadb, skipping load
2024-07-19 03:18:09 - No existing DB found in .chromadb, skipping load
2024-07-19 03:18:09 - No existing DB found in .chromadb, skipping load
2024-07-19 03:18:09 - local variable 'search_engine' referenced before assignment
Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/llm-pdf-qa-sample-app-tlMK2vsn-py3.10/lib/python3.10/site-packages/chainlit/utils.py", line 37, in wrapper
    return await user_function(**params_values)
  File "/home/user/Langchain-LLM-PDF-QA/app/app.py", line 140, in chat
    retriever=search_engine.as_retriever(max_tokens_limit=4097),
UnboundLocalError: local variable 'search_engine' referenced before assignment`

**Comment by kevincw01** [comment]
looks like the gpt3.5 model hard coded in app.py is deprecated by openai.  Changing  model='gpt-4o' and it works now.
